server {
    listen 443;
    server_name dairy.emtechhouse.co.ke;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name dairy.emtechhouse.co.ke;

    root /usr/share/nginx/html/main;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    ssl_certificate /etc/nginx/ssl/certificate.crt;
    ssl_certificate_key /etc/nginx/ssl/private.key;
    ssl_trusted_certificate /etc/nginx/ssl/ca_bundle.crt;

    error_page 404 /index.html;
}
