import { RouteInfo } from "./sidebar.metadata";
export const ROUTES: RouteInfo[] = [
  {
    path: "",
    title: "MAIN",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    submenu: [],
  },

  // Admin Modules
  {
    path: "/admin/dashboard/main",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_ADMIN"],
    submenu: [],
  },

  {
    path: "",
    title: "Configurations",
    moduleName: "meetings",
    iconType: "feather",
    icon: "slack",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_ADMIN"],
    submenu: [
      {
        path: "/admin/business-profile",
        title: "Business Profile",
        moduleName: "profile",
        iconType: "feather",
        icon: "layers",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["ROLE_ADMIN"],
        submenu: [],
      },
      {
        path: "/admin/departments",
        title: "Departments",
        moduleName: "departments",
        iconType: "feather",
        icon: "layers",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["ROLE_ADMIN"],
        submenu: [],
      },
      {
        path: "/admin/counties",
        title: "Counties",
        moduleName: "counties",
        iconType: "feather",
        icon: "layers",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["ROLE_ADMIN"],
        submenu: [],
      },
      {
        path: "/admin/sub-counties",
        title: "Sub Counties",
        moduleName: "subcounties",
        iconType: "feather",
        icon: "layers",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["ROLE_ADMIN"],
        submenu: [],
      },
      {
        path: "/admin/pickup-locations",
        title: "Pick Up Locations",
        moduleName: "pickup",
        iconType: "feather",
        icon: "layers",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["ROLE_ADMIN"],
        submenu: [],
      },
    ],
  },

  {
    path: "",
    title: "User Accounts",
    moduleName: "users",
    iconType: "feather",
    icon: "users",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_ADMIN"],
    submenu: [
      {
        path: "/admin/users",
        title: "All Accounts",
        moduleName: "users",
        iconType: "feather",
        icon: "monitor",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["ROLE_ADMIN"],
        submenu: [],
      },
      {
        path: "/admin/users/collectors",
        title: "Milk Collectors",
        moduleName: "users",
        iconType: "feather",
        icon: "monitor",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["ROLE_ADMIN"],
        submenu: [],
      },
      {
        path: "/admin/users/staff",
        title: "Back Office Staff",
        moduleName: "users",
        iconType: "feather",
        icon: "monitor",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["ROLE_ADMIN"],
        submenu: [],
      },
      {
        path: "/admin/users/sales",
        title: "Sales Team",
        moduleName: "users",
        iconType: "feather",
        icon: "monitor",
        class: "",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["ROLE_ADMIN"],
        submenu: [],
      }
    ],
  },

  {
    path: "/admin/roles",
    title: "User Roles",
    moduleName: "roles",
    iconType: "feather",
    icon: "user-check",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_ADMIN"],
    submenu: [],
  },

  // Staff Modules
  {
    path: "/staff/dashboard/main",
    title: "Dashboard",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_STAFF"],
    submenu: [],
  },
  {
    path: "/staff/farmers/farmers",
    title: "Farmers",
    moduleName: "farmers",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_STAFF"],
    submenu: [],
  },
   {
    path: "/staff/sales/sales",
    title: "Sales",
    moduleName: "sales",
    iconType: "feather",
    icon: "monitor",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ROLE_STAFF"],
    submenu: [],
  },
];
 
  
