import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: 'MAIN',
    moduleName: '',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },

  {
    path: '/admin/dashboard/main',
    title: 'Dashboard',
    moduleName: 'dashboard',
    iconType: 'feather',
    icon: 'monitor',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_ADMIN'],
    submenu: [],
  },

  {
    path: '/admin/dashboard/main',
    title: 'Reports',
    moduleName: 'dashboard',
    iconType: 'feather',
    icon: 'monitor',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_ADMIN'],
    submenu: [],
  },

  {
    path: '/admin/dashboard/main',
    title: 'Logs',
    moduleName: 'dashboard',
    iconType: 'feather',
    icon: 'monitor',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_ADMIN'],
    submenu: [],
  },

  {
    path: '/admin/user-accounts/all',
    title: 'User Management',
    moduleName: 'dashboard',
    iconType: 'feather',
    icon: 'monitor',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_ADMIN'],
    submenu: [],
  },

  {
    path: '/admin/user-accounts/add-account',
    title: 'Add Account',
    moduleName: 'add-account',
    iconType: '',
    icon: '',
    class: 'ml-menu',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [''],
    submenu: [],
  },

  {
    path: '/staff/dashboard/main',
    title: 'Dashboard',
    moduleName: 'dashboard',
    iconType: 'feather',
    icon: 'monitor',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_STAFF'],
    submenu: [],
  },
  {
    path: '/staff/sales/collections',
    title: 'Collections',
    moduleName: 'sales',
    iconType: 'feather',
    icon: 'layers',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_STAFF'],
    submenu: [],
  },
  {
    path: '/staff/farmers/farmers',
    title: 'Farmers',
    moduleName: 'farmers',
    iconType: 'feather',
    icon: 'cloud-rain',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_STAFF'],
    submenu: [],
  },
  {
    path: '/staff/administrator/bulk-upload',
    title: 'Upload Milk Collection',
    moduleName: 'milk-collection',
    iconType: 'feather',
    icon: 'upload-cloud',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_STAFF'],
    submenu: [],
  },

  {
    path: '/staff/sales/sales',
    title: 'Payment Records',
    moduleName: 'sales',
    iconType: 'feather',
    icon: 'shopping-cart',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_STAFF'],
    submenu: [],
  },

  {
    path: '/staff/configs',
    title: 'Price Management',
    moduleName: 'users',
    iconType: 'feather',
    icon: 'slack',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_STAFF'],
    submenu: [],
  },

  {
    path: '/staff/cans',
    title: 'Delivery Cans',
    moduleName: 'milk-cans',
    iconType: 'feather',
    icon: 'thermometer',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_STAFF'],
    submenu: [],
  },

  {
    path: '/staff/stock-categories',
    title: 'Stock Categories',
    moduleName: 'stock-categories',
    iconType: 'feather',
    icon: 'server',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_STAFF'],
    submenu: [],
  },
  {
    path: '/staff/inventory',
    title: 'Inventory Management',
    moduleName: 'inventory',
    iconType: 'feather',
    icon: 'database',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_STAFF'],
    submenu: [],
  },

  {
    path: '/staff/sales/products/sales',
    title: 'Products Allocations',
    moduleName: 'sales',
    iconType: 'feather',
    icon: 'shopping-bag',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_STAFF'],
    submenu: [],
  },
  {
    path: '/reports/main',
    title: 'Reports',
    moduleName: 'reports',
    iconType: 'feather',
    icon: 'file-text',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_STAFF'],
    submenu: [],
  },
  {
    path: '',
    title: 'Bulk SMS',
    moduleName: 'sms',
    iconType: 'feather',
    icon: 'message-square',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_STAFF'],
    submenu: [
      {
        path: '/staff/sms/template',
        title: 'SMS Templates',
        moduleName: 'sms',
        iconType: 'feather',
        icon: 'message-square',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['ROLE_STAFF'],
        submenu: [],
      },
      {
        path: '/staff/sms/bulk',
        title: 'Send Bulk SMS',
        moduleName: 'sms',
        iconType: 'feather',
        icon: 'message-square',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['ROLE_STAFF'],
        submenu: [],
      },
    ],
  },
  {
    path: '/staff/payment-management',
    title: 'Payment Management',
    moduleName: 'payment-management',
    iconType: 'feather',
    icon: 'dollar-sign',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_STAFF'],
    submenu: [],
  },
];
