import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: 'MAIN',
    moduleName: '',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },

  {
    path: '/admin/dashboard/main',
    title: 'Dashboard',
    moduleName: 'dashboard',
    iconType: 'feather',
    icon: 'monitor',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_ADMIN'],
    submenu: [],
  },

  {
    path: '/admin/reports/reports',
    title: 'Reports',
    moduleName: 'dashboard',
    iconType: 'feather',
    icon: 'bar-chart-2',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_ADMIN'],
    submenu: [],
  },

  // {
  //   path: '/admin/reports/reports-handling',
  //   title: 'Reports Handling',
  //   moduleName: 'dashboard',
  //   iconType: 'feather',
  //   icon: 'bar-chart-2',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['ROLE_ADMIN'],
  //   submenu: [],
  // },

  {
    path: '/admin/logs/logs',
    title: 'Logs',
    moduleName: 'dashboard',
    iconType: 'feather',
    icon: 'activity',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_ADMIN'],
    submenu: [],
  },

  {
    path: '/admin/user-accounts/all',
    title: 'User Management',
    moduleName: 'dashboard',
    iconType: 'feather',
    icon: 'users',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_ADMIN'],
    submenu: [],
  },

  {
    path: '/admin/user-accounts/add-account',
    title: 'Add Account',
    moduleName: 'add-account',
    iconType: '',
    icon: '',
    class: 'ml-menu',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [''],
    submenu: [],
  },

  {
    path: '/auditor/dashboard/main',
    title: 'Dashboard',
    moduleName: 'dashboard',
    iconType: 'feather',
    icon: 'monitor',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_AUDITOR'],
    submenu: [],
  },

  {
    path: '/auditor/reports/reports',
    title: 'Reports',
    moduleName: 'dashboard',
    iconType: 'feather',
    icon: 'bar-chart-2',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_AUDITOR'],
    submenu: [],
  },

  {
    path: '/auditor/logs/logs',
    title: 'Logs',
    moduleName: 'dashboard',
    iconType: 'feather',
    icon: 'activity',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_AUDITOR'],
    submenu: [],
  },

  {
    path: '/riskofficer/dashboard/main',
    title: 'Dashboard',
    moduleName: 'dashboard',
    iconType: 'feather',
    icon: 'monitor',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_RISKOFFICER'],
    submenu: [],
  },

  {
    path: '/riskofficer/reports/reports',
    title: 'Reports',
    moduleName: 'dashboard',
    iconType: 'feather',
    icon: 'bar-chart-2',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_RISKOFFICER'],
    submenu: [],
  },
];
