name: Bahati Dairy Angular App Deployment

on:
  push:
    branches:
      - michael  # Deploy only when changes hit my branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm i --force

    - name: Build Angular app
      run: npm run build

    - name: Deploy to AWS Dairy EC2 Instance
      env:
        PRIVATE_KEY: ${{ secrets.DAIRY_KEY }}
        HOST: ${{ secrets.DAIRY_HOST }}
        USER: ${{ secrets.DAIRY_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        scp -o StrictHostKeyChecking=no -i private_key.pem -r dist/* $USER@$HOST:/var/www/dev/
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST "sudo systemctl restart nginx"
